/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/glb/3d-cat.glb -o src/3d-cat.jsx 
Author: sekiri (https://sketchfab.com/sekiri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sleeping-cat-acb0b2565d3a4618ad1e242013f8e3a4
Title: sleeping cat
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cat(props) {
  const { nodes, materials } = useGLTF('/glb/3d-cat.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['material0000.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['material0001.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['material0002.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['material0003.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/3d-cat.glb')
